[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'

remappings = [
	"@openzeppelin/=lib/openzeppelin-contracts/",
	"forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 100
multiline_func_header = 'all'
pragma = 'sortable'

[rpc_endpoints]
eth = '${ETH_RPC_URL}'
monad = '${MONAD_RPC_URL}'
